site_name: Turret Expansion
site_url: https://kanaede.github.io/MindustryExpansions/
repo_url: https://github.com/kanaede/MindustryExpansion
theme:
  name: material
  custom_dir: overrides
  logo: assets/favicon-me.png
  favicon: assets/favicon-me.png
  features:
    - navigation.tracking

extra_css:
  - 'stylesheets/main.css'